name: 'Request Reviewers with Added Label'
description: ''
author: 'marty-s-miyake'
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
  request_reviewers:
    description: 'pull request reviewer list.'
    required: true
    default: '.github/workflows/esmeralda/pr_reviewers.json'
  slack_wehbook:
    description: 'slack incoming webhook url.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
